/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FilterPopup: typeof import('./components/filter-popup/filter-popup.vue')['default']
    PageWraper: typeof import('./components/page-wraper/page-wraper.vue')['default']
    Price: typeof import('./components/price/price.vue')['default']
    PrivacyPopup: typeof import('./components/privacy-popup/privacy-popup.vue')['default']
    WuiButton: typeof import('elegant-wui-uni/components/wui-button/wui-button.vue')['default']
    WuiConfigProvider: typeof import('elegant-wui-uni/components/wui-config-provider/wui-config-provider.vue')['default']
    WuiGap: typeof import('elegant-wui-uni/components/wui-gap/wui-gap.vue')['default']
    WuiIcon: typeof import('elegant-wui-uni/components/wui-icon/wui-icon.vue')['default']
    WuiLoading: typeof import('elegant-wui-uni/components/wui-loading/wui-loading.vue')['default']
    WuiMessageBox: typeof import('elegant-wui-uni/components/wui-message-box/wui-message-box.vue')['default']
    WuiNavbar: typeof import('elegant-wui-uni/components/wui-navbar/wui-navbar.vue')['default']
    WuiNavbarCapsule: typeof import('elegant-wui-uni/components/wui-navbar-capsule/wui-navbar-capsule.vue')['default']
    WuiNotify: typeof import('elegant-wui-uni/components/wui-notify/wui-notify.vue')['default']
    WuiOverlay: typeof import('elegant-wui-uni/components/wui-overlay/wui-overlay.vue')['default']
    WuiPopup: typeof import('elegant-wui-uni/components/wui-popup/wui-popup.vue')['default']
    WuiTabbar: typeof import('elegant-wui-uni/components/wui-tabbar/wui-tabbar.vue')['default']
    WuiTabbarItem: typeof import('elegant-wui-uni/components/wui-tabbar-item/wui-tabbar-item.vue')['default']
    WuiToast: typeof import('elegant-wui-uni/components/wui-toast/wui-toast.vue')['default']
    WuiTransition: typeof import('elegant-wui-uni/components/wui-transition/wui-transition.vue')['default']
  }
}
